### PR TITLE
Avoid jest watch race condition

### LINKED ISSUE #112: Setup race condition with Jest watch results in a ResourceInUseException
Hello.

When running with jest watch, when jest re-runs tests, Setup fails with a `ResourceInUseException` on setup.js line 65. I'm using the latest version of jest-dynamodb, v2.1.0.

Here's the debug logging right before the failure:

```
jest-dynamodb fallback to launch DB due to TypeError: Cannot destructure property 'TableNames' of '(intermediate value)' as it is undefined.
jest-dynamodb dynamodb-local is ready on port 8000
```

The type error is caused by https://github.com/shelfio/jest-dynamodb/blob/8be18c932d8626a67d72d4827a4c15412d81df40/setup.js#L41-L44

Although jest-dynamodb (correctly) does not stop dynamodb-local in Teardown, `waitForLocalhost` wins the race against `dynamoDB.listTables({})`.

I believe the solution is if dynamodb-local is still running during Setup, don't wait for localhost.

### PR DESCRIPTION
**Pull request by EvanOxfeld**
Fixes #112

### CODE REVIEW

File: setup.js [hunk 1]
```diff
@@ -70,7 +73,5 @@ async function createTables(dynamoDB, tables) {
 }
 
 async function deleteTables(dynamoDB, tableNames) {
-  return Promise.all(
-    tableNames.map(tableName => dynamoDB.deleteTable({TableName: tableName}).promise())
```
Comment (randomhash) [inline setup.js:74]: Hey! Thank you for your contribution.

Why do you want to remove .promise() here?

Comment (EvanOxfeld) [reply setup.js:74]: @randomhash Thanks for reviewing! `.promise()` failed for me because `jest-dynamodb` uses AWS SDK v3 but `.promise()` is only part of the AWS SDK v2 API.

`.promise()` is required with v2 because [deleteTable v2](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#deleteTable-property) returns an `AWS.Request` with a `promise` method that must be called. Instead, in v3 [deleteTable](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/classes/dynamodb.html#deletetable) returns a `Promise`.

Also see the [Migrating to AWS SDK v3 guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html#path2-examples) which includes an example of removing `.promise()` calls when upgrading to AWS SDK v3.

**Comment by ruipaulo** [comment]
Hi, could this be merged? This bug is really slowing us down in development as --watch is unusable currently.

**Review by vladgolubev — APPROVED** [review]

**Comment by vladgolubev** [comment]
Published https://github.com/shelfio/jest-dynamodb/releases/tag/v2.2.2
